### ISSUE TITLE
Document Structures

### ISSUE THREAD

**Issue by jfirwin** [jfirwin/meshtastic-documentation#6]
I'm thinking that it would make sense to have this type of layout for our documents, in order to reduce duplication. Putting this out here to promote some discussion. Let me know what you think!

- Getting Started
  - Supported Hardware (landing page with all radios listed, along with links for different marketplaces) (maybe in a table?)
    - Radio A (details about the radio, its operation, spec sheets, etc) (I'd like to keep this to TBeam/heltec/pinephone whatever and include v1-vXYZ on these pages have a feature list table comparing versions or something)
    - Radio B
    - Radio C
  - Flash Firmware (basic high level explanation, CLI vs GUI, link to latest build, etc)
    - Linux (include specifics for CLI/GUI that weren't addressed above)
    - MacOS (for example, `brew -v` if this command returns nothing, install homebrew on Mac using link to homebrew site)
    - Windows
  - Using the Device
    - Button Behavior
    - Pairing (with and without screen)
    - Viewing Serial Logs
- Device Configuration
  - Device Settings
  - Plugins (descriptions of each plugin)
    - Plugin A (examples and documentation using each plugin)
    - Plugin B
    - Plugin C
  - Antenna Section (brief)
- Software (Overview table of all projects, links to repos or "source code")
  - Meshtastic Android (this section I'd like to be more of a brief summary, pointing to each project so that they can be worked on there)
  - Meshtastic iOS
  - Meshtastic PyGUI
  - Meshtastic Python API
  - Meshtastic CLI
  - Meshtastic.js
  - Meshtastic Device
  - Plugins
    - Plugin A
    - Plugin B
    - Plugin C
- Examples (fun section to show off what meshtastic is capable of)
  - The Jungle Project
  - Backpacking
  - Search and Rescue
- FAQ (as we see questions arise in the forum we can add them)

**Comment by apt105** [comment]
I think that's probably a good starting point for a layout. Could also including things like how to set up a development environment,  community thingyverse links to cases and the like. I also half wonder about a page called common problems, but wonder if it might be better to place the problems within the page for the particular section.

**Comment by jfirwin** [comment]
Yes! I totally spaced adding cases (mine are still uncased), I think that would fit well under either the getting started section or the supported hardware.

concerning the common problems, I think thats where I'd like to improve the Frequently Asked Questions section. The answer can have a link to the appropriate documentation, but a brief explanation can be given as well.

**Comment by apt105** [comment]
I do like the idea of giving examples of how the project has been used in different settings though, especially if we can get people to do good write ups of their projects. I'm contemplating a use case of above ground communications on caving expeditions, where camp is often in a different valley from the caves, and if I can build a small solar relay station, I'd happily do a build log to go in that section.

**Comment by jfirwin** [comment]
That would be awesome. I love that idea, thats exactly what I hope to show off in the examples section.
